CursoMVC/CapaPresentacionAdmin/Controllers/AccesoController.cs
using CapaEntidad;
using CapaNegocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CapaPresentacionAdmin.Controllers
{
    public class AccesoController : Controller
    {
        // GET: Acceso
        public ActionResult Index()
        {
            bool cambioClaveExitoso = TempData["CambioClaveExitoso"] != null && (bool)TempData["CambioClaveExitoso"];

            if (cambioClaveExitoso)
            {
                ViewBag.MensajeCambioClave = "Cambio de clave exitoso. Ingrese nuevamente con sus credenciales.";
            }

            // Resto de la lógica para la acción Index

            return View();
        }


        public ActionResult CambiarClave()
        {
            return View();
        }


        public ActionResult Reestablecer()
        {
            return View();
        }



        [HttpPost]
        public ActionResult Index(string correo, string clave)
        {
            Usuario oUsuario = new Usuario();
            oUsuario = new CN_Usuarios().Listar().Where(u => u.Correo == correo && u.Clave == CN_Recursos.ConvertirSha256(clave)).FirstOrDefault();

            if (oUsuario == null)
            {
                ViewBag.Error = "Correo o contraseña Incorrecta";
                return View();
            }
            else {
                if (oUsuario.Reestablecer)
                {
                    TempData["idUsuario"] = oUsuario.idUsuario;
                    return RedirectToAction("CambiarClave");

                }

                ViewBag.Error = null;
                return RedirectToAction("Index", "Home");
            }

        }


        [HttpPost]
        public ActionResult CambiarClave(string idusuario, string claveactual, string nuevaclave, string confirmarclave)
        {
            Usuario oUsuario = new Usuario();
            oUsuario = new CN_Usuarios().Listar().Where(u => u.idUsuario == int.Parse(idusuario)).FirstOrDefault();

            if(oUsuario.Clave != CN_Recursos.ConvertirSha256(claveactual))
            {

                TempData["idUsuario"] = idusuario;
                ViewData["vclave"] = "";
                ViewBag.Error = "La contraseña actual no es correcta";
                return View();
            }
            else if(nuevaclave != confirmarclave)
            {
                TempData["idUsuario"] = idusuario;
                ViewData["vclave"] = claveactual;
                ViewBag.Error = "Las Nuevas Contraseñas no Coinciden";
                return View();
            }
            ViewData["vclave"] = "";

            nuevaclave = CN_Recursos.ConvertirSha256(nuevaclave);

            string mensaje = string.Empty;

            bool respuesta = new CN_Usuarios().CambiarClave(int.Parse(idusuario), nuevaclave, out mensaje);

            if (respuesta)
            {
                TempData["CambioClaveExitoso"] = true;
                return RedirectToAction("Index");
            }
            else {
                TempData["idUsuario"] = idusuario;
                ViewBag.Error = mensaje;
                return View();
            }
        }
    }
}

CursoMVC/CapaPresentacionAdmin/Views/Acceso/CambiarClave.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CambiarClave</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <style>
        /* Otros estilos pueden ir aquí */

        footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            background-color: #f8f9fa; /* Fondo de color claro */
            padding: 15px; /* Espaciado interno */
        }
    </style>

</head>
<body style="background:black">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        @*<div class="col-lg-7">*@
                            <div class="col-lg-7" style="box-shadow: 0 0 20px rgb(0, 38, 255); margin-top:10px">

                                <div >
                                    <div class="card-header">
                                        <h3 class="text-center font-weight-light my-4" style="color:white">Cambiar Contraseña</h3>
                                    </div>
                                    <div class="card-body">
                                        <form action="@Url.Action("CambiarClave", "Acceso")" method="post">

                                            <input class="form-control" type="hidden" value="@TempData["idUsuario"] " name="idusuario" />


                                            <div class="row mb-3">
                                                <div class="col-md-12">
                                                    <div class="form-floating mb-3 mb-md-0">
                                                        <input class="form-control" id="claveactual" type="password" name="claveactual" value="@ViewData["vclave"]" ; />
                                                        <label for="inputPassword">Contraseña Actual</label>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row mb-3">
                                                <div class="col-md-12">
                                                    <div class="form-floating mb-3 mb-md-0">
                                                        <input class="form-control" id="nuevaclave" type="password" name="nuevaclave" />
                                                        <label for="inputPassword">Nueva Contraseña</label>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="row mb-3">
                                                <div class="col-md-12">
                                                    <div class="form-floating mb-3 mb-md-0">
                                                        <input class="form-control" id="confirmarclave" type="password" name="confirmarclave" />
                                                        <label for="inputPassword">Confirmar Nueva Contraseña</label>
                                                    </div>
                                                </div>
                                            </div>

                                            @{
                                            if (ViewBag.Error != null)
                                            {
                                        <div class="row mb-3">
                                            <div class="col-md-12">
                                                <div class="alert alert-danger" role="alert">
                                                    @ViewBag.Error
                                                </div>
                                            </div>
                                        </div>
                                            }
                                            }
                                            <div class="mt-4 mb-0">
                                                <div class="d-grid">
                                                <button class="btn btn-primary btn-block" type="submit" onclick="cambiarContrasena()">Cambiar Contraseña</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="card-footer text-center py-3">
                                        <div class="small"><a href="@Url.Action("Index","Acceso")">Volver</a></div>
                                    </div>
                                </div>
                            </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">

            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">SISTEMAS &copy; Carrito de Compras 2024</div>
                        <div>
                            <a href="#">Política de Privacidad</a>
                            &middot;
                            <a href="#">Términos &amp; Condiciones</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>


    </div>
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
    function cambiarContrasena() {
        // Coloca aquí tu lógica para realizar el cambio de contraseña

        // Después del cambio exitoso, muestra el mensaje usando Swal.fire
        Swal.fire({
            icon: 'success',
            title: 'Cambio de Contraseña Exitoso',
            text: 'Debe iniciar sesión con sus nuevas credenciales.',
            showConfirmButton: false,
            timer: 3000 // Muestra el mensaje durante 3 segundos antes de cerrarse automáticamente
        });
    }
    </script>

</body>
</html>

CursoMVC/CapaPresentacionAdmin/Views/Acceso/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/Site.css" rel="stylesheet" />


    <style>
        /* Otros estilos pueden ir aquí */

        footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            background-color: #f8f9fa; /* Fondo de color claro */
            padding: 15px; /* Espaciado interno */
        }
    </style>









</head>
<body style="background:black">

    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container"  >
                    <div class="row justify-content-center" >
                        <div class="col-lg-5" style="box-shadow: 0 0 20px rgb(0, 38, 255); margin-top:20px" >
                                    <div class="card-header">
                                        <h3 class="text-center font-weight-light my-4" style="color:white">Login</h3>
                                    </div>
                                    <div class="card-body">
                                            <form action="@Url.Action("Index", "Acceso")" method="post" onsubmit="return validateForm()">

                                                <div class="form-floating mb-3">
                                                    <input class="form-control" name="correo" id="correo" type="email" placeholder="name@example.com" autocomplete="username" />
                                                    <label for="correo">Correo Electrónico</label>
                                                </div>


                                                <div class="form-floating mb-3">
                                                    <input class="form-control" name="clave" id="clave" type="password" placeholder="Password" autocomplete="current-password" />
                                                    <label for="clave">Contraseña</label>
                                                </div>

                                                         @{
                                                            if (ViewBag.Error != null)
                                                            {
                                                                <div class="form-floating mb-3">
                                                                    <div class="alert alert-danger" role="alert">
                                                                        @ViewBag.Error
                                                                    </div>
                                                                </div>
                                                                }
                                                            }



                                                <div class="form-check mb-3">
                                                    <input class="form-check-input" id="inputRememberPassword" type="checkbox" value="" />
                                                    <label class="form-check-label" for="inputRememberPassword" style="color:gray">Recordar Contraseña</label>
                                                </div>
                                                <div class="d-flex align-items-center justify-content-between mt-4 mb-0">
                                                    <a class="small" href="password.html">Has Olvidado tu Contraseña ?</a>
                                                    <button type="submit" class="btn btn-primary">Iniciar Sesion</button>
                                                </div>
                                            </form>
                                    </div>

                                    <div class="card-footer text-center py-3">
                                        <div class="small"><a href="register.html">¿Necesito una cuenta? ¡Inscribirse!</a></div>
                                    </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">SISTEMAS &copy; Carrito de Compras 2024</div>
                        <div>
                            <a href="#">Política de Privacidad</a>
                            &middot;
                            <a href="#">Términos &amp; Condiciones</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    
    </div>

    <!-- Mensaje de Cambio de Clave Exitoso -->
    @if (ViewBag.MensajeCambioClave != null)
    {
        <div class="alert alert-success text-center">
            @ViewBag.MensajeCambioClave
        </div>
    }



    <script src="~/Scripts/bootstrap.bundle.js"></script>
    <script>
    
        function validateForm() {
            var correo = document.getElementById('correo').value.trim();
            var clave = document.getElementById('clave').value.trim();


            if (correo === '' && clave === '') {
                alert('Todos Los Campos Estan Vacios, Completar.');
                return false; // Evita que el formulario se envíe si ambos campos están vacíos
            }

            if (correo === '') {
                alert('Por favor, completa el campo Correo.');
                return false; // Evita que el formulario se envíe si los campos están vacíos
            }

            if (clave === '') {
                alert('Por favor, Ingresar la contraseña');
                return false; // Evita que el formulario se envíe si los campos están vacíos
            }

    

            // Si todos los campos están completos, el formulario se enviará
            return true;
        }


    </script>

</body>